# Generated by Django 2.1.3 on 2018-11-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='company/client name')),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('referral', models.CharField(blank=True, max_length=254, null=True, verbose_name='referral source')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='company/client name')),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=128)),
                ('last', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='project name')),
                ('number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='job number')),
                ('started', models.DateField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('billed', models.FloatField(blank=True, null=True)),
                ('construction_cost', models.FloatField(blank=True, null=True)),
                ('is_dam', models.BooleanField(null=True, verbose_name='is it a dam?')),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('watershed', models.FloatField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('flood_volume', models.FloatField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sitereport.Client')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='sitereport.Contractor')),
                ('dam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dam_type', to='sitereport.DamType')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase', to='sitereport.Phase')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('travel_time', models.FloatField(blank=True, null=True)),
                ('site_time', models.FloatField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('weather', models.CharField(max_length=64)),
                ('conditions', models.CharField(max_length=128, verbose_name='site conditions')),
                ('description', models.TextField(blank=True, null=True, verbose_name='work description')),
                ('photos', models.TextField(blank=True, null=True, verbose_name='Drive/Dropbox link to photos')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('street', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=10)),
                ('date_start', models.DateField(blank=True, default=None, null=True, verbose_name='date started')),
                ('date_end', models.DateField(blank=True, default=None, null=True, verbose_name='date ended')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sitereport.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SpillwayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_sites', to='sitereport.UsState'),
        ),
        migrations.AddField(
            model_name='report',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_reports', to='sitereport.Site'),
        ),
        migrations.AddField(
            model_name='report',
            name='tests',
            field=models.ManyToManyField(blank=True, to='sitereport.TestType'),
        ),
        migrations.AddField(
            model_name='project',
            name='spillway_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spillway_type', to='sitereport.SpillwayType'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='sitereport.Status'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='sitereport.Person'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_contractors', to='sitereport.UsState'),
        ),
        migrations.AddField(
            model_name='client',
            name='decider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_maker', to='sitereport.Person'),
        ),
        migrations.AddField(
            model_name='client',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_lead', to='sitereport.Person'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_clients', to='sitereport.UsState'),
        ),
    ]
