# Generated by Django 2.1.3 on 2018-11-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitereport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='client_people', to='sitereport.Person'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='contractor_people', to='sitereport.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_group', to='sitereport.Role'),
        ),
    ]
