# Generated by Django 2.1.3 on 2018-11-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitereport', '0005_project_ended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='width',
            new_name='length',
        ),
    ]
