# Generated by Django 2.1.3 on 2018-11-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitereport', '0006_auto_20181119_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
