# Generated by Django 2.1.3 on 2018-11-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitereport', '0007_auto_20181113_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_clients', to='sitereport.UsState'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sitereport.Client'),
        ),
        migrations.AlterField(
            model_name='site',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sitereport.Project'),
        ),
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_sites', to='sitereport.UsState'),
        ),
    ]
