# Generated by Django 2.1.3 on 2018-11-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitereport', '0009_auto_20181114_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('travel_time', models.FloatField(blank=True, null=True)),
                ('site_time', models.FloatField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('weather', models.CharField(max_length=64)),
                ('conditions', models.CharField(max_length=128, verbose_name='site conditions')),
                ('description', models.TextField(blank=True, null=True, verbose_name='work description')),
                ('photos', models.TextField(blank=True, null=True, verbose_name='Drive/Dropbox link to photos')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_reports', to='sitereport.Site')),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='tests',
            field=models.ManyToManyField(blank=True, to='sitereport.TestType'),
        ),
    ]
